site_name: Tingbot Docs
repo_url: https://github.com/tingbot/tingbot-docs/
theme: readthedocs
extra_css: [extra.css]
extra_javascript: [extra.js]
markdown_extensions:
    - toc
    - admonition
pages:
- Home: 'index.md'
- Tide: 'tide.md'
- User Guide:
    - 'Setting up Tingbot': 'guides/setup.md'
    - 'Writing your first app': 'guides/first-app.md'
    - 'Touch and buttons': 'guides/touch-buttons.md'
    # - 'Consuming web APIs': 'guides/web-apis.md'
    # - 'Using Python modules': 'guides/python-modules.md'
    - 'Publishing to Tingbot Ocean': 'guides/publish-to-ocean.md'
# - Examples:
    # - Tide bundled examples page
- Reference:
    - 'tingbot-python': 'links/tingbot-python-docs.md'
    - 'The tingapp format': 'reference/tingapp-format.md'
    - 'Tingbot OS': 'reference/tingbot-os.md'
- Links:
    # - 'Forum': 'links/forum.md'
    - 'Tingbot Ocean': 'links/ocean.md'
    - 'Github': 'links/github.md'
    # - 'The Tingbot Shop': 'links/shop.md'
